# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-06 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0002_auto_20160502_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfBasic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confbasic_id', models.IntegerField()),
                ('name', models.CharField(max_length=128)),
                ('start_date', models.DateTimeField(db_index=True)),
                ('end_date', models.DateTimeField(db_index=True)),
                ('location', models.CharField(max_length=256)),
                ('image', models.CharField(max_length=256)),
                ('version', models.IntegerField()),
                ('private_type', models.IntegerField()),
                ('color', models.CharField(max_length=64)),
                ('sequence', models.CharField(max_length=256)),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ConfDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confid', models.IntegerField()),
                ('preview_code', models.CharField(max_length=128)),
                ('zipcode', models.CharField(max_length=16)),
                ('desc', models.CharField(max_length=256)),
                ('poster', models.CharField(max_length=256)),
                ('org', models.CharField(max_length=128)),
                ('website', models.CharField(max_length=256)),
                ('reg_url', models.CharField(max_length=256)),
                ('phone', models.CharField(max_length=32)),
                ('fax', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=128)),
                ('weibo', models.CharField(max_length=64)),
                ('weixin', models.CharField(max_length=64)),
                ('qq', models.CharField(max_length=16)),
                ('longitude', models.CharField(max_length=32)),
                ('latitude', models.CharField(max_length=32)),
                ('timeZone', models.CharField(max_length=32)),
                ('privateType', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('email', models.CharField(max_length=256)),
                ('unionId', models.CharField(max_length=256)),
            ],
        ),
    ]
