# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-07 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0003_confbasic_confdetail_userlogin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlogin',
            name='email',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
