# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-07 13:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0004_auto_20161207_1940'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
