# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-30 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0008_userlogin_confid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confbasic',
            name='end_date',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='confbasic',
            name='location',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='confbasic',
            name='start_date',
            field=models.DateTimeField(db_index=True, null=True),
        ),
    ]
