# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-30 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0009_auto_20161230_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confbasic',
            name='private_type',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='confbasic',
            name='status',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='confbasic',
            name='version',
            field=models.IntegerField(null=True),
        ),
    ]
