# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-30 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0010_auto_20161230_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='InConf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('confid', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='userlogin',
            name='confid',
        ),
    ]
